version: '2'
services:

    python-flask:
        build: ./python-flask
        ports:
            - "5000:5000"
        networks:
          - backend-network
          - frontend-network

    nginx:
        build: ./nginx
        restart: always
        ports:
          - 80:80
        depends_on:
          - python-flask
        networks:
          - backend-network
          - frontend-network

networks:
  backend-network:
  frontend-network: